config/routes.rb
Rails.application.routes.draw do
resources :films
resources :planets
resources :characters
resources :starships
resources :searchs

root 'films#index'  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
		include Metodos

  def show
	url = request.original_url
	@id = get_id(url).to_i


	res = HTTParty.get('https://swapi.co/api/people/'+@id.to_s, :headers => {'Content-Type' => 'application/json'}).body
	@character = JSON.parse(res)


	planets_urls = @character["homeworld"]
	@planets_names = request_urls_single(planets_urls, "name")

	starships_urls = @character["starships"]
	@starships_names = request_urls(starships_urls, "name")

	films_urls = @character["films"]
	@films_titles = request_urls(films_urls, "title")
  end

end

app/controllers/concerns/metodos.rb
module Metodos
	extend ActiveSupport::Concern

	def get_id(url)
		id = url.split("/")[-1]
		return id
	end 

	def api_request(url)
		response = HTTParty.get(url, :headers => {'Content-Type' => 'application/json'}).body
		res_json = JSON.parse(response)
		id = get_id(url)
		return res_json, id
	end 

	def api_response(res_json, attribute)
		attr_response = res_json["attribute"]
		return
	end

    def request_urls(urls, attribute)
	  	lista_res = []
	  	urls.each do |url|
	  		res_json, id = api_request(url)
	  		needed = [res_json[attribute], id]
	  		lista_res << needed
	  	end
	  	return lista_res
	end 

    def request_urls_single(urls, attribute)
	  		res_json, id = api_request(urls)
	  		needed = [res_json[attribute], id]
	  	return needed
	end 


	def searching(keyword)
		lista_res = []

		res_films = HTTParty.get('https://swapi.co/api/films/?search='+keyword.to_s, :headers => {'Content-Type' => 'application/json'}).body
		films = JSON.parse(res_films)["results"]
		films.each do |film|
			film_id = get_id(film["url"])
			found = [film["title"],film_id,"films"]
			lista_res << found
		end

		res_starships = HTTParty.get('https://swapi.co/api/starships/?search='+keyword.to_s, :headers => {'Content-Type' => 'application/json'}).body
		starships = JSON.parse(res_starships)["results"]
		iterar = JSON.parse(res_starships)["next"]

		starships.each do |starship|
			starship_id = get_id(starship["url"])
			found = [starship["name"],starship_id,"starships"]
			lista_res << found
		end

		while iterar.present?
			res_starships = HTTParty.get(iterar+'/?search='+keyword.to_s, :headers => {'Content-Type' => 'application/json'}).body
			iterar = JSON.parse(res_starships)["next"]
			starships.each do |starship|
				starship_id = get_id(starship["url"])
				found = [starship["name"],starship_id,"starships"]
				lista_res << found
		end
		end

		res_chars = HTTParty.get('https://swapi.co/api/people/?search='+keyword.to_s, :headers => {'Content-Type' => 'application/json'}).body
		chars = JSON.parse(res_chars)["results"]
		iterar = JSON.parse(res_chars)["next"]

		chars.each do |char|
			char_id = get_id(char["url"])
			found = [char["name"],char_id,"characters"]
			lista_res << found
		end

		while iterar.present?
			res_char = HTTParty.get(iterar+'/?search='+keyword.to_s, :headers => {'Content-Type' => 'application/json'}).body
			iterar = JSON.parse(res_chars)["next"]
			chars.each do |char|
				char_id = get_id(char["url"])
				found = [char["name"],char_id,"characters"]
				lista_res << found
		end
		end

		res_planets = HTTParty.get('https://swapi.co/api/planets/?search='+keyword.to_s, :headers => {'Content-Type' => 'application/json'}).body
		planets = JSON.parse(res_planets)["results"]
		iterar = JSON.parse(res_planets)["next"]

		planets.each do |planet|
			planet_id = get_id(planet["url"])
			found = [planet["name"],planet_id,"planets"]
			lista_res << found
		end

		while iterar.present?
			res_planets = HTTParty.get(iterar+'/?search='+keyword.to_s, :headers => {'Content-Type' => 'application/json'}).body
			iterar = JSON.parse(res_planets)["next"]
			planets.each do |planet|
				planet_id = get_id(planet["url"])
				found = [planet["name"],planet_id,"planets"]
				lista_res << found
		end
		end

		return lista_res

	end

end 

app/controllers/films_controller.rb
require 'httparty'
require 'pp'
require 'json'



class FilmsController < ApplicationController
	include Metodos

  def index
	response = HTTParty.get('https://swapi.co/api/films', :headers => {'Content-Type' => 'application/json'}).body
	@films = JSON.parse(response)["results"]  	 
  end

  def show
	url = request.original_url
	@id = get_id(url).to_i

	res = HTTParty.get('https://swapi.co/api/films/'+@id.to_s, :headers => {'Content-Type' => 'application/json'}).body
	@film = JSON.parse(res)

	planets_urls = @film["planets"]
	@planets_names = request_urls(planets_urls, "name")


	char_urls = @film["characters"]
	@characters_names = request_urls(char_urls, "name")

	starships_urls = @film["starships"]
	@starships_names = request_urls(starships_urls, "name")


  end


end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
		include Metodos

  def show
	url = request.original_url
	@id = get_id(url).to_i


	res = HTTParty.get('https://swapi.co/api/planets/'+@id.to_s, :headers => {'Content-Type' => 'application/json'}).body
	@planet = JSON.parse(res)

	films_urls = @planet["films"]
	@films_titles = request_urls(films_urls, "title")

	char_urls = @planet["residents"]
	@characters_names = request_urls(char_urls, "name")
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
	include Metodos

  def index

    @search = params["search"]
    if @search.present?
      @lista_res = searching(@search["search"])
    end
  end



end

app/controllers/starships_controller.rb
class StarshipsController < ApplicationController
		include Metodos

  def show
	url = request.original_url
	@id = get_id(url).to_i


	res = HTTParty.get('https://swapi.co/api/starships/'+@id.to_s, :headers => {'Content-Type' => 'application/json'}).body
	@starship = JSON.parse(res)

	char_urls = @starship["pilots"]
	@characters_names = request_urls(char_urls, "name")

	films_urls = @starship["films"]
	@films_titles = request_urls(films_urls, "title")
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/starships_helper.rb
module StarshipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/characters/show.html.erb
<div class="jumbotron">
  <div class="container">


		<p><b>Name:</b> <%= @character["name"] %></p>
		<p><b>Birth year:</b> <%= @character["birth_year"] %></p>
		<p><b>Eye color:</b> <%= @character["eye_color"] %></p>
		<p><b>Gender:</b> <%= @character["gender"] %></p>
		<p><b>Hair color:</b> <%= @character["hair_color"] %></p>
		<p><b>Height:</b> <%= @character["height"] %></p>
		<p><b>Mass:</b> <%= @character["mass"] %></p>
		<p><b>Skin color:</b> <%= @character["skin_color"] %></p>


		<p><b>Homeworld:</b> <% @planets_names %>
					-<a href="/planets/<%= @planets_names[1]%>"><%= @planets_names[0] %></a>
		</p>

		<p><b>Films:</b> <% @films_titles.each do |film| %>
					-<a href="/films/<%= film[1]%>"><%= film[0] %></a>
						<% end %>
		</p>

		<p><b>Starships:</b> <% @starships_names.each do |starship| %>
					-<a href="/starships/<%= starship[1]%>"><%= starship[0] %></a>
						<% end %>
		</p>


		<p><b>URL Source:</b> <%= @character["url"] %></p>
		<p><b>Created:</b> <%= @character["created"] %></p>
		<p><b>Edited:</b> <%= @character["edited"] %></p>



  </div>
</div>

app/views/films/index.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">

	<% @films.each do |f| %>
				<% film_id = (f["url"].split("/")[-1]).to_i%>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">

      <div class="caption">
        <h3><%= f["title"] %></h3>
		<p><b>Release Date:</b> <%= f["release_date"] %></p>
		<p><b>Episode ID:</b> <%= f[ "episode_id"] %> </p>
		<p><b>Director:</b> <%= f["director"] %> </p>
		<p><b>Producer:</b> <%= f["producer"] %> </p>
        <p><a href="/films/<%=film_id%>" class="btn btn-primary" role="button">More Info</a></p>
      </div>
    </div>
  </div>
		<% end %>


</div>
  </div>
</div>

app/views/films/show.html.erb
<div class="jumbotron">
  <div class="container">


		<p><b>Title:</b> <%= @film["title"] %></p>
		<p><b>Episode number:</b> <%= @film["episode_id"] %></p>
		<p><b>Opening crawl:</b> <%= @film["opening_crawl"] %></p>
		<p><b>Director:</b> <%= @film["director"] %></p>
		<p><b>Producer:</b> <%= @film["producer"] %></p>
		<p><b>Release date:</b> <%= @film["release_date"] %></p>


		<p><b>Starships:</b> <% @starships_names.each do |starship| %>
					-<a href="/starships/<%= starship[1]%>"><%= starship[0] %></a>
						<% end %>
		</p>


		<p><b>Characters:</b> <% @characters_names.each do |char| %>
					-<a href="/characters/<%= char[1]%>"><%= char[0] %></a>
						<% end %>
		</p>


		<p><b>Planets:</b> <% @planets_names.each do |planet| %>
					-<a href="/planets/<%= planet[1]%>"><%= planet[0] %></a>
						<% end %>
		</p>


		<p><b>URL Source:</b> <%= @film["url"] %></p>
		<p><b>Created:</b> <%= @film["created"] %></p>
		<p><b>Edited:</b> <%= @film["edited"] %></p>



  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taller1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/films/">Star Wars Movies</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/films/">Home <span class="sr-only">(current)</span></a>
      </li>
   

    </ul>
        <%= simple_form_for :search, url: searchs_path, method: "GET", html: { class: 'form-inline my-2 my-lg-0' } do |f| %>
        <%= f.input :search, label: false, input_html: {value: ""} %>   
        <%= f.submit "Search", class: "btn btn-outline-success btn-sm" %>
        <% end %>
  </div>
</nav>



    <%= yield %>
  </body>
</html>

app/views/planets/show.html.erb
<div class="jumbotron">
  <div class="container">


		<p><b>Name:</b> <%= @planet["name"] %></p>
		<p><b>Diameter:</b> <%= @planet["diameter"] %></p>
		<p><b>Rotation Period:</b> <%= @planet["rotation_period"] %></p>
		<p><b>Orbital Period:</b> <%= @planet["orbital_period"] %></p>
		<p><b>Gravity:</b> <%= @planet["gravity"] %></p>
		<p><b>Population:</b> <%= @planet["population"] %></p>
		<p><b>Climate:</b> <%= @planet["climate"] %></p>
		<p><b>Terrain:</b> <%= @planet["terrain"] %></p>
		<p><b>Surface Water:</b> <%= @planet["surface_water"] %></p>

		<p><b>Residents:</b> <% @characters_names.each do |char| %>
					-<a href="/characters/<%= char[1]%>"><%= char[0] %></a>
						<% end %>
		</p>

		<p><b>Films:</b> <% @films_titles.each do |film| %>
					-<a href="/films/<%= film[1]%>"><%= film[0] %></a>
						<% end %>
		</p>


		<p><b>URL Source:</b> <%= @planet["url"] %></p>
		<p><b>Created:</b> <%= @planet["created"] %></p>
		<p><b>Edited:</b> <%= @planet["edited"] %></p>


  </div>
</div>

app/views/searchs/index.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">

<% @lista_res.each do |f| %>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">

      <div class="caption">
        <h4><%= f[0] %></h4>
        <p><%= f[2] %></p>
        <p><a href="/<%=f[2]%>/<%=f[1]%>" class="btn btn-primary" role="button">More Info</a></p>
      </div>
    </div>
  </div>
    <% end %>



</div>
  </div>
</div>

app/views/starships/show.html.erb
<div class="jumbotron">
  <div class="container">


		<p><b>Name:</b> <%= @starship["name"] %></p>
		<p><b>Model:</b> <%= @starship["model"] %></p>
		<p><b>Starship class:</b> <%= @starship["starship_class"] %></p>
		<p><b>Manufacturer:</b> <%= @starship["manufacturer"] %></p>
		<p><b>Cost in credits:</b> <%= @starship["cost_in_credits"] %></p>
		<p><b>Length:</b> <%= @starship["length"] %></p>
		<p><b>Crew:</b> <%= @starship["crew"] %></p>
		<p><b>Passengers:</b> <%= @starship["passengers"] %></p>
		<p><b>Max speed:</b> <%= @starship["max_atmosphering_speed"] %></p>
		<p><b>Hyperdrive rating:</b> <%= @starship["hyperdrive_rating"] %></p>
		<p><b>MGLT:</b> <%= @starship["MGLT"] %></p>
		<p><b>Cargo capacity:</b> <%= @starship["cargo_capacity"] %></p>
		<p><b>Consumables: <%= @starship["consumables"] %></p>

		<p><b>Films:</b> <% @films_titles.each do |film| %>
					-<a href="/films/<%= film[1]%>"><%= film[0] %></a>
						<% end %>
		</p>

		<p><b>Residents:</b> <% @characters_names.each do |char| %>
					-<a href="/characters/<%= char[1]%>"><%= char[0] %></a>
						<% end %>
		</p>

		<p><b>URL Source:</b> <%= @starship["url"] %></p>
		<p><b>Created:</b> <%= @starship["created"] %></p>
		<p><b>Edited:</b> <%= @starship["edited"] %></p>


  </div>
</div>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
  <%= FilmsController.new.show %>

</p>